
spring.cloud.config.parent:
  application: demo-app-common
  label: master # must quote, if not the 'spring.cloud.config.parent.label: {label}' will becomes 'spring.cloud.config.parent.label.label: ', tested on spring-boot:1.5.12.RELEASE
  # token generate by /encryptParentPassword:
  # eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbmNyeXB0ZWQiOiJBUUJTNkhOdUkrRU5vZVgrM0N0Y0p1OTFPYUREbmhSWS8xOERRYmpUbjFkWncxbzZqODFacktxc05ZUXhvNW9XRmp6Ung0RWxUOEVUcmxodTRnVzh4Z3R0L21jaEc4bEZkMkFMcVU3aEpkQmlDT0hZdVhBYThmZ1NScDNKUUdvUmVxeTVJYVJEdHVOcWNLQlJRRUlYYi9PRzhHR2xEaHQyY3UrMFFEdTNoeEhFdVZOenJRaGYvV2RlM2lTUjlZU3ovSmp6K2RMSGhIdEJtbEVEZXExKzZKaERpVE1yYWdoNFk5WUxPTmlkVFRtUG1hdUtreUxqYnJkUFNWUEtKdFN1dTdyem9NT3Y2cnp2dEpwZTJQYTZJai9ob1pDNHcxQUd2TmNYZmNIQlJEeHZucFZWRGJLWTRYKzUxUXhSMmUxL3hJSWtrRXR0L251Y1hmSlJWSkE3NEdiTDY5dUU2WGFTODc3dmhwdEdPa1lDWTkwWFZhSXVQOEhsK2ZmOGc1TlJWSjJOZGNnS3FEOEN4VmNCTzBXVHQxZjJIVDZ3TDlGZ1R4anI1QnNUSHBVSmZZcHBEdHVNS094VFhqV1Z4Tk93RUFDbC9GdnFpQXNNYk1yYUp6TjFKUGNNb2U1bThjQjR5T2NUVzBKa3F0dUpSWGExNmViVFBCbHlxcGpOYjhxYXZxREIwdlRVWFBEWVB0Kzc0MHBYYUNsYmVBVGRTZDR2cGp5MGtCcXRMcFF2TVZ5RzJDdThuSndzYjVpZmxlbVJlR0tnV2VFTk9weW83b2p6dlRERk1DZ1djd0krR0FUSXNBR2ZMT0dJSFZablNSZ1dqUHRMdlpIZk9ZdmlWckgrYmdvPSIsImlzcyI6ImNvbmZpZy1zZXJ2ZXIiLCJleHAiOjE2ODU5MDEwNzJ9.u9n89MGKXnmkiIGsctmpcUWEgoB6CFCpIMCJX32cmdg
  # plain text:
  # demo-app-common_pass
  password: 'demo-app-common_pass'

spring.cloud.config.password: demo-app_pass

profile-sensitive: demo-app-config_none

in-demo-app-only: in-demo-app-only

in-both-demo-app-common-and-demo-app: demo-app

demo-app-label-sensitive: master

---
spring:
  profiles: default

profile-sensitive: demo-app-config_default

---
spring:
  profiles: development.env

profile-sensitive: demo-app-config_development.env

---
spring:
  profiles: ut.env

profile-sensitive: demo-app-config_ut.env

---
spring:
  profiles: it.env

profile-sensitive: demo-app-config_it.env

---
spring:
  profiles: staging.env

profile-sensitive: demo-app-config_staging.env

---
spring:
  profiles: production.env

profile-sensitive: demo-app-config_production.env
